version: '3.9'

services:
    rpi-temp-checker:
        build: .
        ports:
            - "8080:8080"
        privileged: true
        environment:
            - "HIGH_TEMP=55.0"
            - "CRITICAL_TEMP=70.0"
            - "GPIO_PIN=2"
            - "TIMEOUT=10"