name: Build Docker

on:
  push:
    branches:
      - 'develop'
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Latest Tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: Tert0/futurecloud-backend
        id: latest_tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          push: true
          tags: tert0/rpi-temp-checker:latest, tert0/rpi-temp-checker:${{ steps.latest_tag.outputs.tag }}